// <auto-generated />
namespace Cevehat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _662018440 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_662018440));
        
        string IMigrationMetadata.Id
        {
            get { return "201806061444132_6-6-2018-4.40"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
