// <auto-generated />
namespace Cevehat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_user_applied_to_job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_user_applied_to_job));
        
        string IMigrationMetadata.Id
        {
            get { return "201806111450276_Add_user_applied_to_job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
