// <auto-generated />
namespace Cevehat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adddate_state_toVacancy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddate_state_toVacancy));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081347541_Add-date_state_toVacancy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
