// <auto-generated />
namespace Cevehat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_un : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_un));
        
        string IMigrationMetadata.Id
        {
            get { return "201806181542107_remove_un"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
