// <auto-generated />
namespace Cevehat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Last_update_of_database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Last_update_of_database));
        
        string IMigrationMetadata.Id
        {
            get { return "201806121042412_Last_update_of_database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
